method=overlay
tiles= 0-13 <skip> 15 <skip>
faces=sides
connectBlocks=yellow_terracotta
matchBlocks= cut_sandstone smooth_sandstone stone_bricks infested_stone_bricks cracked_stone_bricks mossy_stone_bricks cut_red_sandstone smooth_red_sandstone resin_block resin_bricks chiseled_resin_bricks pale_oak_wood stripped_pale_oak_wood pale_oak_log stripped_pale_oak_log poplar_wood stripped_poplar_wood poplar_log stripped_poplar_log

